In [18]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os 
os.getcwd()

'c:\\Users\\hamoud\\Desktop\\Fraud_detection'

In [19]:
train_data = pd.read_csv("creditcard_train_scaled.csv")
test_data = pd.read_csv("creditcard_test_scaled.csv")
train_data

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,scaled_amount,scaled_time,Class
0,-0.917597,1.468375,1.607758,-0.021990,-0.283089,-1.229240,0.753631,-0.146383,-0.231226,0.272734,...,-0.441894,0.050339,0.924543,-0.120948,0.043518,0.484835,0.256764,-0.289650,-0.369625,0
1,-0.699142,0.319290,2.278452,0.736121,-0.684040,0.742862,0.375170,0.367698,-0.234212,-0.523238,...,0.993618,0.085713,0.224880,-0.032720,-0.288623,0.090848,0.074140,1.510490,-0.290133,0
2,-0.571369,1.317794,1.019639,1.021975,-0.042067,-0.127407,0.277220,0.433044,-1.207277,-0.179688,...,0.703393,-0.196171,0.041482,-0.135509,-0.215535,0.043891,0.080868,-0.128951,-0.350920,0
3,1.147507,-1.921087,-0.261885,1.487177,-0.829881,1.908747,-0.955687,0.517632,1.752487,-0.071405,...,0.604139,-0.294560,-0.384808,-0.231287,-0.544888,0.037585,0.036367,5.265734,0.394304,0
4,-0.629345,0.848104,1.146756,0.566688,0.934798,0.073785,0.859693,-0.066140,-0.817268,-0.399711,...,0.023712,-0.422906,-0.992322,0.739840,-0.111136,0.050766,0.068694,0.348951,-0.571407,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227840,0.095639,0.101785,1.261669,-1.375506,-0.519103,-0.233864,-0.100928,-0.147033,-1.281357,0.323678,...,0.105428,-0.029562,-0.351602,-0.957453,1.370403,0.143042,0.177850,-0.096503,0.013436,0
227841,-6.046362,-1.285178,-2.486027,0.271327,-3.502477,0.974063,0.025943,2.182822,0.245799,-1.772681,...,-0.193982,0.159401,-0.541897,-0.645865,0.715113,0.107730,-1.271921,4.024615,-0.047256,0
227842,0.033797,0.882025,0.306073,-0.583187,0.450910,-1.128918,1.033273,-0.231043,-0.107794,-0.422426,...,-0.536077,0.069324,0.050828,-0.475434,0.136317,0.249307,0.098713,-0.257483,0.837261,0
227843,-2.011805,0.510858,0.773423,-1.790730,0.866647,0.349700,0.598281,-0.007178,0.760874,0.809981,...,-0.180485,0.168770,-1.270998,-0.036114,0.810049,0.351317,0.070897,0.111888,-0.347517,0
227844,-1.959402,1.997522,0.345605,-0.305297,-0.642357,-0.538113,-0.135870,0.942992,-0.329781,0.440685,...,-0.633464,0.066853,-0.027007,0.011540,0.079430,0.198059,0.157961,-0.181958,-0.452603,0

In [20]:
X_train = train_data.drop(columns="Class")
y_train = train_data["Class"]
print(X_train.shape,y_train.shape)

(227845, 30) (227845,)

In [21]:
X_test = test_data.drop(columns="Class")
y_test = test_data["Class"]
print(X_test.shape,y_test.shape)

(56962, 30) (56962,)

Model training:

Lets create a function that will evaluate and store the models results

In [22]:
import pandas as pd

results_df = pd.DataFrame(columns=[
    "Model",
    "Precision (Non-Fraud)", "Recall (Non-Fraud)", "F1 (Non-Fraud)",
    "Precision (Fraud)", "Recall (Fraud)", "F1 (Fraud)",
    "ROC-AUC"
])

Logistic regression

In [23]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(random_state=42)

In [24]:
from crossval_report import print_crossval_results
lr_model = LogisticRegression(random_state=42)
crossval_result = print_crossval_results(lr_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.871, Recall=0.602, F1=0.712

In [25]:
lr_model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [26]:
y_test_pred = lr_model.predict(X_test)
y_test_proba = lr_model.predict_proba(X_test)[:, 1]
from store_results import store_and_print_results
results_df = store_and_print_results(results_df, "Logistic Rression (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== Logistic Rression (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.887, Recall=0.643, F1=0.746
ROC-AUC: 0.988

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716

Logistic Regression Results

1. Cross-Validation (on training set with CV = 5):

    Class 0 (Non-Fraud): Precision = 0.999, Recall = 1.000, F1 = 1.000

    Class 1 (Fraud): Precision = 0.871, Recall = 0.602, F1 = 0.712

    The model detects almost all non-fraud transactions perfectly.

    Fraud detection is weaker (recall 0.602), which is common with highly imbalanced datasets.

2. Test Set Evaluation:

    Class 0 (Non-Fraud): Precision = 0.999, Recall = 1.000, F1 = 1.000

    Class 1 (Fraud): Precision = 0.887, Recall = 0.643, F1 = 0.746

    Performance slightly improves on the test set for fraud detection.

RandomForest

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight=None  
)
crossval_result= print_crossval_results(rf_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.945, Recall=0.787, F1=0.859

In [28]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [29]:
y_test_pred = rf_model.predict(X_test)
y_test_proba = rf_model.predict_proba(X_test)[:, 1]

In [30]:
results_df = store_and_print_results(results_df, "Random Forest (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== Random Forest (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.950, Recall=0.776, F1=0.854
ROC-AUC: 0.957

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835

1.  Cross-Validation (on training set)

        Class 0 (Non-Fraud): Precision, Recall, F1 = 1.0 → almost perfect at identifying legitimate transactions.

        Class 1 (Fraud):

        Precision = 0.945 → most predicted frauds are truly fraud.

        Recall = 0.787 → ~79% of actual frauds are correctly detected.

        F1 = 0.859 → solid balance between precision and recall for fraud.

2.  Test Set (Unbalanced Random Forest)

        Class 0 (Non-Fraud): Still perfect.

        Class 1 (Fraud):

        Precision = 0.950 → slightly better than CV.

        Recall = 0.776 → slightly lower than CV.

        F1 = 0.854 → very close to CV, showing good generalization.

Non-Fraud Class: Model is enar-perfetct for detecting non-Fraud Class

Fraud Class: Random Forest has higher precision (0.95 vs 0.887) than Logistic Regression, meaning fewer false positives. Recall is also higher (0.776 vs 0.643), meaning more frauds are correctly detected. F1 reflects this improvement.

SGD + Logistic Regression

In [31]:
from sklearn.linear_model import SGDClassifier
sgd_lr = SGDClassifier(
    loss='log_loss',           
    max_iter=1000,        
    tol=1e-3,             
    class_weight=None,    
    random_state=42
)
crossval_result= print_crossval_results(sgd_lr, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.842, Recall=0.556, F1=0.670

In [32]:
sgd_lr.fit(X_train,y_train)

SGDClassifier(loss='log_loss', random_state=42)

In [33]:
y_test_pred = sgd_lr.predict(X_test)
y_test_proba = sgd_lr.predict_proba(X_test)[:, 1]

In [34]:
results_df = store_and_print_results(results_df, "SGD_LR (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== SGD_LR (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.881, Recall=0.602, F1=0.715
ROC-AUC: 0.988

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565

During 5-fold cross-validation on the training set:

        Non-Fraud (Class 0): Precision, Recall, and F1 are essentially perfect (~1.000), meaning the model almost never misclassifies normal transactions.

        Fraud (Class 1): Precision=0.842, Recall=0.556, F1=0.670 — the model identifies many frauds correctly, but still misses a significant portion (recall is moderate).

On the final test set:

        Non-Fraud: Same excellent metrics as CV, showing stable performance.

        Fraud: Precision improved to 0.881, recall to 0.602, F1 to 0.715 — better than CV, likely due to having seen the full training set during final training.

In [35]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)
crossval_result= print_crossval_results(xgb_model, X_train, y_train, cv=5)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.950, Recall=0.779, F1=0.856

In [36]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [37]:
y_test_pred = xgb_model.predict(X_test)
y_test_proba = xgb_model.predict_proba(X_test)[:, 1]
results_df = store_and_print_results(results_df, "XGBoost (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== XGBoost (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=1.000, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.963, Recall=0.796, F1=0.872
ROC-AUC: 0.986

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961

Cross-Validation:

    Non-Fraud: Perfect metrics (precision, recall, F1 ≈ 1.0)

    Fraud: Precision 0.950, Recall 0.779, F1 0.856 → model detects most fraud cases but misses some (recall < 0.8)

Test Set (Unbalanced):

    Non-Fraud remains perfect

    Fraud improves slightly (Precision 0.963, Recall 0.796, F1 0.872)

    ROC-AUC 0.986 → excellent overall discrimination between classes

SVM

In [38]:
from sklearn.svm import SVC

svm_model = SVC(
    kernel='rbf',      
    C=1.0,             
    gamma='scale',
    probability=True,  
    random_state=42
)
from crossval_report import print_crossval_results
crossval_result = print_crossval_results(svm_model, X_train, y_train, cv=3)
crossval_result

=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.937, Recall=0.645, F1=0.764

In [39]:
svm_model.fit(X_train,y_train)

SVC(probability=True, random_state=42)

In [40]:
y_test_pred = svm_model.predict(X_test)
y_test_proba = svm_model.predict_proba(X_test)[:, 1]
from store_results import store_and_print_results
results_df = store_and_print_results(results_df, "SVM (Unbalanced)", y_test, y_test_pred, y_test_proba)
results_df

=== SVM (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=1.000, F1=1.000
Class 1 (Fraud)    : Precision=0.971, Recall=0.684, F1=0.802
ROC-AUC: 0.940

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961
4,SVM (Unbalanced),0.999455,0.999965,0.999710,0.971014,0.683673,0.802395,0.939697

During 5-fold cross-validation, the SVM model achieved almost perfect performance for the non-fraud class, with precision, recall, and F1-score all close to 1.000. For the fraud class, the model obtained a precision of 0.937, recall of 0.645, and F1-score of 0.764. This indicates that when the model predicts fraud it is usually correct, but it still misses a noticeable number of fraudulent transactions.

When evaluated on the test set, the performance improved slightly. The fraud class achieved a precision of 0.971, recall of 0.684, and F1-score of 0.802. The ROC-AUC score of 0.940 indicates that the model has a strong ability to distinguish between fraudulent and legitimate transactions overall.

LIGHTGBM

In [41]:
from lightgbm import LGBMClassifier
lgbm_model = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=-1,
    num_leaves=31,
    random_state=42
)
crossval_result = print_crossval_results(lgbm_model, X_train, y_train, cv=5)
crossval_result

[LightGBM] [Info] Number of positive: 316, number of negative: 181960
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,006513 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001734 -> initscore=-6,355800
[LightGBM] [Info] Start training from score -6,355800
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 315, number of negative: 181961
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,006739 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001728 -> initscore=-6,358975
[LightGBM] [Info] Start training from score -6,358975
[LightGBM] [Info] Number of positive: 315, number of negative: 181961
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,006600 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001728 -> initscore=-6,358975
[LightGBM] [Info] Start training from score -6,358975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 315, number of negative: 181961
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,006745 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001728 -> initscore=-6,358975
[LightGBM] [Info] Start training from score -6,358975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 315, number of negative: 181961
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,005829 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 182276, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001728 -> initscore=-6,358975
[LightGBM] [Info] Start training from score -6,358975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
=== Cross-Validation Classification Report ===
Class 0 (Non-Fraud): Precision=0.999, Recall=0.998, F1=0.999
Class 1 (Fraud)    : Precision=0.290, Recall=0.487, F1=0.364

In [42]:
lgbm_model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 394, number of negative: 227451
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0,007587 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 227845, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0,001729 -> initscore=-6,358339
[LightGBM] [Info] Start training from score -6,358339

LGBMClassifier(n_estimators=200, random_state=42)

In [43]:
y_test_pred = lgbm_model.predict(X_test)
y_test_proba = lgbm_model.predict_proba(X_test)[:, 1]

results_df = store_and_print_results(
    results_df,
    "LightGBM (Unbalanced)",
    y_test,
    y_test_pred,
    y_test_proba
)

results_df

=== LightGBM (Unbalanced) Classification Report ===
Class 0 (Non-Fraud): Precision=0.998, Recall=0.991, F1=0.995
Class 1 (Fraud)    : Precision=0.022, Recall=0.122, F1=0.038
ROC-AUC: 0.575

,Model,Precision (Non-Fraud),Recall (Non-Fraud),F1 (Non-Fraud),Precision (Fraud),Recall (Fraud),F1 (Fraud),ROC-AUC
0,Logistic Rression (Unbalanced),0.999385,0.999859,0.999622,0.887324,0.642857,0.745562,0.987716
1,Random Forest (Unbalanced),0.999613,0.999930,0.999771,0.950000,0.775510,0.853933,0.956835
2,SGD_LR (Unbalanced),0.999315,0.999859,0.999587,0.880597,0.602041,0.715152,0.987565
3,XGBoost (Unbalanced),0.999648,0.999947,0.999798,0.962963,0.795918,0.871508,0.985961
4,SVM (Unbalanced),0.999455,0.999965,0.999710,0.971014,0.683673,0.802395,0.939697
5,LightGBM (Unbalanced),0.998476,0.990732,0.994589,0.022263,0.122449,0.037677,0.575404